name: main
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

scripts:
  gen: dart run build_runner build

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  args: ^2.1.0
  shelf: ^1.1.2
  shelf_router: ^1.0.0
  shelf_static: ^1.1.0
  mysql1: ^0.19.2
  jaguar_jwt: ^3.0.0
  test: ^1.24.3
  http: ^1.0.0
  io: ^1.0.4
  encrypt: ^5.0.1
  orm: ^3.4.2

dev_dependencies:
  pedantic: ^1.11.0
  shelf_router_generator: ^1.0.0
  build_runner: ^2.0.3